#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : libdeps
Version  : 1
Release  : 1
URL      : http://localhost/cgit/projects/libdeps/snapshot/libdeps-1.tar.gz
Source0  : http://localhost/cgit/projects/libdeps/snapshot/libdeps-1.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-3.0
Requires: libdeps-bin = %{version}-%{release}

%description
No detailed description available

%package bin
Summary: bin components for the libdeps package.
Group: Binaries

%description bin
bin components for the libdeps package.


%prep
%setup -q -n libdeps-1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1546471531
make  %{?_smp_mflags}


%install
export SOURCE_DATE_EPOCH=1546471531
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/libdeps.py
